# Site settings
title: "Cake By The Road"
email: info@cakebytheroad.co.uk
url: https://cakebytheroad.co.uk
description: "Beautiful home-made bakes."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  primary-light: '#ffffff'
  links: '#219ab3'

# Footer settings
footer: www.cakebytheroad.co.uk

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/cakebytheroad
  - title: etsy
    url: https://www.etsy.com/uk/shop/HandmadeBitsFinds

# Build settings
markdown: kramdown
permalink: pretty
